### PR TITLE
💰 Request command

### PR DESCRIPTION
**Pull request by bdeneux**
#### 📝 Purpose 

Add a new discord slash command allowing user to request token(s) from cosmos blockchain. 

`/request okp41uwn6phyj8q7dl45jn6ksvjuydtuju467g6fy34`

Capture d’écran 2022-08-09 à 11 05 21

#### ⚙️ Configuration

New configurations sections has been added to configure the cosmos chain client and faucet configuration. Here a configuration example : 

```toml
[chain]
chain_id = "okp4-devnet-1"
denom = "uknow"
grpc_address = "https://grpc.devnet.staging.okp4.network:443"
prefix = "okp4"

[faucet]
amount_send = 1000000
fee_amount = 0
gas_limit = 200000
memo = "Sent by økp4 discord bot"
mnemonic = "$MNEMONIC"
```

#### 📟  Tech stack 

Libraries added for this command: 

- [cosmrs](https://github.com/cosmos/cosmos-rust), using the fix https://github.com/cosmos/cosmos-rust/pull/281 and https://github.com/cosmos/cosmos-rust/pull/264 : transaction signature, cosmos proto, queries, ...
- [prost](https://github.com/tokio-rs/prost) : for protobuf queries.

**This command also change the `ExecutableCommand` trait by adding a GRPC connection client for all discord command. By doing this, when `start` discord command is launch, a connection is establishing with the GRPC endpoint then the bot is launch. On each discord command the GRPC client is given to perform query and transaction.**

There is still a lot to do to improve error managing, grpc connection, managing discord command, .... It's the first proposal of implementation, another PR will be created to refactor and improve those things

### CODE REVIEW

**Review by ccamel — APPROVED** [review]
There is still a lot to do to improve the code, but that can be done in a second step.
For me, it's ok to merge it as it is.

Thanks for the work! :+1:

**Review by amimart — APPROVED** [review]
Thank you! I think it needs refactoring but we can merge it and make it in a second time 😉.

By submitting a transaction for each request there is a limitation of one request per block, we should consider to batch messages in the refactoring.

**Review by ingvaar — APPROVED** [review]
Really nice work ! LGTM :+1:

**Review by ad2ien — APPROVED** [review]
:clap: :clap:

**Pull request merged**
